name: curator
windows:
  - server: cargo run --bin curator-server
  - agent: ./wait-for-it.sh localhost:8080 && cargo run --bin curator-agent -- -h localhost:8080
  - requests: cd ./requests
  - npm: cd ./frontend && npm start
