name: curator
windows:
  - server: cargo run --bin curator-server
  - agent: cargo run --bin curator-agent -- -h localhost:8080 -a test -i `hostname`
  - requests: cd ./requests
  - npm: cd ./frontend && npm start
