[package]
name = "curator"
version = "0.1.0"
authors = ["Denis Bazhenov <dotsid@gmail.com>"]
edition = "2018"

[lib]
name = "curator"
path = "src/lib.rs"

[[bin]]
name = "curator-server"
path = "src/server-main.rs"

[[bin]]
name = "curator-agent"
path = "src/agent-main.rs"

[dependencies]
actix-rt = "1.0.0"
actix-server = "1.0.2"
actix-files = "0.2.2"
actix-web = "2.0.0"
actix = "0.9.0"
futures = "0.3.5"
tokio = { version = "0.2.13", features = ["rt-threaded", "macros", "io-util", "process"] }
bytes = "0.5.4"
hyper = "0.13.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.11", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
termion = "1.5.5"
anyhow = "1.0.0"
thiserror = "1.0"
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.0"
tempdir = "0.3.7"
ctrlc = { version = "3.1.4", features = ["termination"] }
bollard = "0.9.1"

[dev-dependencies]
tempfile = "3.1.0"
maplit = "1.0.2"
rstest = "0.6.4"
