[package]
name = "curator"
version = "0.1.0"
authors = ["Denis Bazhenov <dotsid@gmail.com>"]
edition = "2018"

[lib]
name = "curator"
path = "src/lib.rs"

[[bin]]
name = "curator"
path = "src/main.rs"

[[bin]]
name = "curator-client"
path = "src/curator-client.rs"

[dependencies]
actix-rt = "1.0.0"
actix-server = "1.0.2"
actix-web = "2.0.0"
actix = "0.9.0"
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["rt-threaded", "macros", "io-util", "process"] }
#tokio-util = { version = "0.3.1", features = ["codec"] }
bytes = "0.5.4"
hyper = "0.13.4"
error-chain = "0.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde"] }