version: '3.8'
services:
  backend:
    build:
      context: .
      target: curator-server
    environment:
      - RUST_LOG=info

  agent:
    build:
      context: .
      target: curator-agent
    environment:
      - RUST_LOG=curator=warn
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --host backend:8080 --name single

  frontend:
    build:
      context: ./frontend
      target: frontend

  app:
    build:
      context: ./frontend
      target: router
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
  
  # Container with integrations tests
  it-tests:
    build:
      context: .
      target: builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /opt/test-docker
    depends_on:
      - it-sample-container

  it-sample-container:
    image: alpine:3.12
    command: sh -c "read line"
    tty: true
    labels:
      io.kubernetes.pod.name: alpine