version: '3.8'
services:
  backend:
    build:
      context: .
      target: curator-server
    environment:
      - RUST_LOG=curator=info
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"