version: '3.8'
services:
  backend:
    build:
      context: .
      target: curator-server
    environment:
      - RUST_LOG=curator=info
  agent:
    build:
      context: .
      target: curator-agent-dev
    environment:
      - RUST_LOG=curator=info
      - CURATOR_HOST=backend:8080
      - AGENT_NAME=single
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
      target: frontend
  router:
    build:
      context: ./frontend
      target: router
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
  
  it-sample-container:
    image: openjdk:11.0-jdk
    command: sh -c "sleep 2"
    labels:
      io.kubernetes.pod.name: openjdk
  
  # Container with integrations tests
  tests:
    build:
      context: .
      target: builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /opt/test-docker
    depends_on:
      - it-sample-container