version: '3.8'
services:
  backend:
    build:
      context: .
      target: curator-server
    environment:
      - RUST_LOG=curator=warn

  agent:
    build:
      context: .
      target: curator-agent
    environment:
      - RUST_LOG=curator=warn
    depends_on:
      - backend
      - sample-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: run -h backend:8080 -n single -l io.kubernetes.pod.name -t bazhenov.me/curator/toolchain-example:dev

  frontend:
    build:
      context: ./frontend
      target: frontend

  router:
    build:
      context: ./frontend
      target: router
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"
  sample-container:
    image: alpine:3.12
    command: sh -c "read line"
    tty: true
    labels:
      io.kubernetes.pod.name: alpine
  
  # Container with integrations tests
  it-tests:
    build:
      context: .
      target: builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "/opt/test-curator && /opt/test-docker && /opt/test-curator_sse_test"
    depends_on:
      - it-sample-container

  it-sample-container:
    image: alpine:3.12
    command: sh -c "read line"
    tty: true
    labels:
      io.kubernetes.pod.name: alpine