version: '3.8'
services:
  backend:
    build:
      context: .
      target: curator-server
    environment:
      - RUST_LOG=curator=info
  agent:
    build:
      context: .
      target: curator-agent-dev
    environment:
      - RUST_LOG=curator=info
      - CURATOR_HOST=backend:8080
      - CURATOR_APP_NAME=test
      - CURATOR_INSTANCE_NAME=single
    depends_on:
      - backend
  frontend:
    build:
      context: ./frontend
      target: frontend
  router:
    build:
      context: ./frontend
      target: router
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:8080"