version: '3.8'
services:
  backend:
    build:
      context: .
      target: curator-server
    environment:
      - RUST_LOG=curator=info
  agent:
    build:
      context: .
      target: curator-agent-dev
    environment:
      - RUST_LOG=curator=info
    command: --application test --instance single --host frontend:8080
    depends_on:
      - frontend
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"