version: '3.8'
services:
  backend:
    image: curator-server:dev
    environment:
      - RUST_LOG=curator=info
  frontend:
    image: curator-frontend:dev
    depends_on:
      - backend
    ports:
      - "8080:8080"